//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbWebAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long IDX { get; set; }
        public string UserId { get; set; }
        public string PassHash { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
