//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbWebAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long IDX { get; set; }
        public string Title { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public bool Released { get; set; }
    }
}
